hosts = LDAP_HOSTS_PLACEHOLDER

dn = LDAP_BIND_DN_PLACEHOLDER
dnpass = LDAP_BIND_PW_PLACEHOLDER

auth_bind = no
ldap_version = 3

base = LDAP_BASE_DN_PLACEHOLDER
scope = subtree

user_filter = (&(objectClass=inetOrgPerson)(uid=%n))
pass_filter = (&(objectClass=inetOrgPerson)(uid=%n))

pass_attrs = userPassword=password
user_attrs = =uid=vmail, =gid=vmail, =home=/var/mail/%u
